server:
  port: ${random.int(10000,19999)}

spring:
  cloud:
    nacos:
      server-addr: 47.114.134.109:8848
      discovery:
        namespace: dev
        cluster-name: order
      config:
        server-addr: 47.114.134.109:8848 # Nacos 服务器地址
        namespace: dev # 使用的 Nacos 的命名空间，默认为 null
        group: one # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
        name: # 使用的 Nacos 配置集的 dataId，默认为 spring.application.name
        file-extension: yaml # 使用的 Nacos 配置集的 dataId 的文件拓展名，同时也是 Nacos 配置集的配置格式，默认为 properties
  loadbalancer:
    retry:
      enabled: true

order:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  # Ribbon 饥饿加载配置项，对应 RibbonEagerLoadProperties 配置类
  # 是否开启饥饿加载。默认为 false 不开启
  ConnectTimeout: 100 # 请求的连接超时时间，单位：毫秒。默认为 1000
  ReadTimeout: 1 # 请求的读取超时时间，单位：毫秒。默认为 1000
  OkToRetryOnAllOperations: true # 是否对所有操作都进行重试，默认为 false。
  MaxAutoRetries: 0 # 对当前服务的重试次数，默认为 0 次。
  MaxAutoRetriesNextServer: 1 # 重新选择服务实例的次数，默认为 1 次。注意，不包含第 1 次哈。
  restclient:
    enabled: true
  eager-load:
    enabled: true
    clients: order
#ribbon:
#  okhttp:
#    enabled: true # 设置使用 OkHttp，对应 OkHttpRibbonConfiguration 配置类
#  restclient:
#    enabled: true # 设置使用 Jersey Client，对应 RestClientRibbonConfiguration 配置类
#  httpclient:
#    enabled: true # 设置使用 Apache HttpClient，对应 HttpClientRibbonConfiguration 配置类
logging:
  level:
    src.service: DEBUG

feign:
  # Feign 客户端配置，对应 FeignClientProperties 配置属性类
  client:
    # config 配置项是 Map 类型。key 为 Feign 客户端的名字，value 为 FeignClientConfiguration 对象
    config:
      # 全局级别配置
      default:
        logger-level: BASIC
      # 客户端级别配置
      order:
        logger-level: FULL
        feign:
  # Feign Apache HttpClient 配置项，对应 FeignHttpClientProperties 配置属性类
  #HttpClientFeignLoadBalancedConfiguration
  httpclient:
    enabled: true # 是否开启。默认为 true
    max-connections: 200 # 最大连接数。默认为 200
    max-connections-per-route: 50 # 每个路由的最大连接数。默认为 50。router = host + port
  #OkHttpFeignLoadBalancedConfiguration
  okhttp:
    enabled: false
