spring:
  application:
    name: gateway-application
  main:
    #nacos里面有个标记为废弃的bean -NacosRefreshProperties,NacosConfigAutoConfiguration
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        cluster-name: gateway
        group: one
        service: ${spring.application.name}

gateway-application:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule